- name: Create custom Docker networks
  community.docker.docker_network:
    name: "{{ item.name }}"
    driver: bridge
    driver_options:
      com.docker.network.bridge.name: "{{ item.bridge }}"
    state: present
  loop:
    - { name: "management", bridge: "management" }
    - { name: "monitoring", bridge: "monitoring" }
    - { name: "torrent", bridge: "torrent" }
    - { name: "guacd", bridge: "guacd" }
    - { name: "logging", bridge: "logging" }


- name: Create docker deploy path
  file:
    path: "{{ DEPLOY_PATH }}/stack-management/"
    state: directory
    recurse: yes

- name: Create environment file
  template:
    src: ".env.j2"
    dest: "{{ DEPLOY_PATH }}/stack-management/.env"
    mode: '0640'

- name: Generate portainer password (raw)
  community.general.htpasswd:
    path: "{{ DEPLOY_PATH }}/stack-management/portainer_password_file.raw"
    hash_scheme: "bcrypt"
    name: admin
    password: "{{ PORTAINER_PASSWORD }}"
    mode: '0640'

- name: Slurp bcrypt password
  ansible.builtin.slurp:
    src: "{{ DEPLOY_PATH }}/stack-management/portainer_password_file.raw"
  register: passwordfile

- name: Set fact with escaped bcrypt password
  set_fact:
    PORTAINER_PASSWORD_BCRYPT: >-
      {{ (passwordfile.content | b64decode).split(':', 1)[1] | replace('$', '$$') | trim }}

- name: Remove portainer password file
  ansible.builtin.file:
    path: "{{ DEPLOY_PATH }}/stack-management/portainer_password_file.raw"
    state: absent
  
- name: Generate Traefik password
  community.general.htpasswd:
    path: "{{ DEPLOY_PATH }}/stack-management/usersfile"
    name: admin
    password: "{{ TRAEFIK_ENTRYPOINT }}"
    mode: '0640'

- name: Generate docker-compose
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ DEPLOY_PATH }}/stack-management/docker-compose.yml"
    mode: '0644'

- name: Deploy the stack
  community.docker.docker_compose:
    project_src: "{{ DEPLOY_PATH }}/stack-management"
    state: present
