apiVersion: v1
kind: Service
metadata:
  name: cloudflared
  namespace: management
spec:
  selector:
    app: cloudflared
  ports:
  - name: metrics
    port: 60123
    targetPort: 60123
  type: ClusterIP
