apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          ports:
            - containerPort: 3306
              name: mysql

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_ROOT_PASSWORD

            - name: BOOKSTACK_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: BOOKSTACK_DB_PASSWORD

            - name: GUACAMOLE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: GUACAMOLE_DB_PASSWORD

          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d/001-create-databases.sh
              subPath: 001-create-databases.sh

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data

        - name: mysql-init
          configMap:
            name: mysql-init
            defaultMode: 0755