apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstack-config
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: bookstack-local
  hostPath:
    path: /srv/k3s/applications/bookstack
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-config
  namespace: applications
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: bookstack-local
  resources:
    requests:
      storage: 10Gi
