{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bookstack.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ include "bookstack.ingressHost" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bookstack.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
