{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.volumeName }}
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  hostPath:
    path: {{ .Values.persistence.hostPath }}
    type: {{ .Values.persistence.hostPathType }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.claimName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
