services:
  mysql:
    container_name: mysql
    image: mysql:latest
    networks:
      - database
    labels:
      - "logaggregation=yes"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=sqadmin
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ${CONFIG_PATH:-.}/mysql/schema:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD | grep 'mysqld is alive' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

 
networks:
  database:
    external: true

volumes:
  mysql-data: 
    name: mysql-data
