apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
  namespace: management
type: Opaque
stringData:
  TUNNEL_TOKEN: "eyJhIjoiZWJhYTdmY2I4NDU0ZjAwMjhiNTkxNzUzZjQ5OTZmM2YiLCJ0IjoiNjljZGIxOGEtMWZlZS00NzA0LWIyYTItMzk3MGM1YjU5MjlmIiwicyI6Ik16VmtNalF5WXpJdFpqZGxPUzAwWW1ZNUxUZ3pPV0V0WVRaa05HVXpNemRrWlRReCJ9"