apiVersion: v1
kind: Secret
metadata:
  name: portainer-secret
  namespace: management
type: Opaque
stringData:
  PORTAINER_LICENSE_KEY: "3-Gyu+NVt8bR7LmN5OqUzd92+GdL36tGy469IQ3InBoNhymTJ2MIL+nNWTJHRemVdMHl0bRrBUEnB0KZAjrOc54OG3FSP5qpfGfRWCGkz85EmPOXqHQrk7Awu9+f1Fhv4Cwd4="
