- name: Create dir for deployment
  file:
    path: "{{ DEPLOY_PATH }}/monitoring-stack/"
    state: directory
    mode: '0755'
    recurse: yes

- name: Create config subdirectories
  file:
    path: "{{ DEPLOY_PATH }}/monitoring-stack/config/{{ item }}"
    state: directory
    mode: '0755'
    recurse: yes
  loop:
    - grafana/dashboards
    - grafana/provisioning/dashboards
    - grafana/provisioning/datasources
    - prometheus

- name: Deploy static Grafana config files
  copy:
    src: "config/{{ item }}"
    dest: "{{ DEPLOY_PATH }}/monitoring-stack/config/{{ item }}"
    mode: "0644"
  loop:
    - grafana/dashboards/cloudflared.json
    - grafana/dashboards/node-exporter.json
    - grafana/dashboards/openwrt.json
    - grafana/dashboards/traefik.json
    - grafana/provisioning/dashboards/cloudflared.yml
    - grafana/provisioning/dashboards/node-exporter.yml
    - grafana/provisioning/dashboards/openwrt.yml
    - grafana/provisioning/dashboards/traefik.yml
    - grafana/provisioning/datasources/prometheus.yml

- name: Template docker-compose.yml
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ DEPLOY_PATH }}/monitoring-stack/docker-compose.yml"
    mode: "0644"

- name: Deploy Monitoring stack
  uri:
    url: "http://{{ HOST }}:9000/api/stacks/create/standalone/string?endpointId={{ ENDPOINT_ID }}"
    method: POST
    headers:
      Authorization: "Bearer {{ portainer_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      Name: "monitoring"
      StackFileContent: "{{ lookup('file', DEPLOY_PATH + '/monitoring-stack/docker-compose.yml') }}"
      ComposeFormat: "3"
      EndpointID: {{ ENDPOINT_ID | default(1) }}
    status_code: [200, 409]
    timeout: 300
  register: stack_create_result