apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: qbittorrent

  template:
    metadata:
      labels:
        app: qbittorrent

    spec:
      securityContext:
        fsGroup: 1001

      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest

          env:
            - name: PUID
              value: "1001"

            - name: PGID
              value: "1001"

            - name: TZ
              value: "PlaceHolder"

          ports:
            - name: webui
              containerPort: 8080

          volumeMounts:
            - name: config
              mountPath: /config

            - name: data
              mountPath: /downloads

      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config

        - name: data
          persistentVolumeClaim:
            claimName: qbittorrent-data