apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-data-pv
spec:
  capacity:
    storage: 1Ti

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: qbittorrent-local

  local:
    path: PLACEHOLDER

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ubuntu-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-data
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: qbittorrent-local

  resources:
    requests:
      storage: 1Ti

  volumeName: qbittorrent-data-pv