global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
  
  - job_name: OpenWrt
    static_configs:
      - targets: [192.168.0.2:9123]
  
  - job_name: cloudflared
    static_configs:
      - targets: [cloudflared:60123]