services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - TZ=${TZ:-Europe/Warsaw}
      - APP_KEY=${APP_KEY}
      - APP_URL=https://wiki.${HOST}
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USERNAME=sqadmin           
      - DB_PASSWORD=${DB_PASSWORD}  
      - DB_DATABASE=bookstack_db 
    volumes:
      - bookstack-data:/config
    labels:
      - "logaggregation=yes"
      - "traefik.enable=true"
      - "traefik.http.routers.bookstack.rule=Host(`wiki.${HOST}`)"
      - "traefik.http.services.bookstack.loadbalancer.server.port=80"
      - "traefik.docker.network=applications"
    restart: unless-stopped
    networks:
      - database
      - applications
      
networks:
  database:
    external: true
  applications:
    external: true

volumes:
  bookstack-data: 
    name: bookstack-data