replicaCount: 1

image:
  repository: qbittorrentofficial/qbittorrent-nox
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  port: 8080

ingress:
  enabled: true
  className: traefik
  host: ""
  subdomain: qb
  domain: tanello.site

env:
  QBT_LEGAL_NOTICE: confirm
  WEBUI_PORT: "8080"
  TZ: Europe/Warsaw

securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

persistence:
  config:
    enabled: true
    existingClaim: ""
    claimName: qbittorrent-config
    volumeName: qbittorrent-config
    storageClassName: qbittorrent-config-local
    accessMode: ReadWriteOnce
    size: 5Gi
    reclaimPolicy: Retain
    hostPath: /srv/k3s/applications/qbittorrent
    hostPathType: DirectoryOrCreate
    mountPath: /config
  downloads:
    enabled: true
    existingClaim: ""
    claimName: qbittorrent-downloads
    volumeName: qbittorrent-downloads
    storageClassName: qbittorrent-local
    accessMode: ReadWriteOnce
    size: 800Gi
    reclaimPolicy: Retain
    hostPath: /srv/samba/torrent
    hostPathType: Directory
    mountPath: /downloads

resources: {}
