apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: portainer-local
  hostPath:
    path: /srv/k3s/management/portainer
    type: Directory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-config
  namespace: management
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: portainer-local
  resources:
    requests:
      storage: 10Gi
