apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: alloy

  template:
    metadata:
      labels:
        app: alloy

    spec:
      serviceAccountName: alloy

      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: alloy
          image: grafana/alloy:latest

          securityContext:
            allowPrivilegeEscalation: false

            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false

            runAsUser: 0
            runAsGroup: 0

          resources:
            requests:
              cpu: 100m
              memory: 512Mi

          args:
            - run
            - --server.http.listen-addr=0.0.0.0:12345
            - /etc/alloy/config.alloy

          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

          volumeMounts:
            - name: data
              mountPath: /var/lib/alloy/data

            - name: tmp
              mountPath: /tmp

            - name: config
              mountPath: /etc/alloy
              readOnly: true

            - name: varlog
              mountPath: /var/log
              readOnly: true

      volumes:
        - name: data
          emptyDir: {}

        - name: tmp
          emptyDir: {}

        - name: config
          configMap:
            name: alloy-config

        - name: varlog
          hostPath:
            path: /var/log
            type: Directory