apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database

resources:
  - service.yaml
  - storage.yaml
  - deployment.yml
  - namespace.yml

generatorOptions:
  disableNameSuffixHash: true


secretGenerator:
  - name: mysql-secret
    envs:
      - envs/mysql-secrets.env