- name: Deploy guacamole Stack
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../group_vars/vars/all.yml
    - ../group_vars/vars/guacamole.yml
    - ../group_vars/vault/guacamole.yml
    - ../group_vars/vault/management.yml

  roles:
    - portainer-api-login
    - deploy-filebrowser