apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yml
  - middleware.yml

secretGenerator:
  - name: traefik-dashboard-auth
    namespace: management
    files:
      - usersfile

generatorOptions:
  disableNameSuffixHash: true
