apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adguard.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adguard.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "adguard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "adguard.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "adguard.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.env }}
          env:
            {{- range $name, $value := .Values.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          ports:
            - name: dns-udp
              containerPort: {{ .Values.service.dnsUdpPort }}
              protocol: UDP
              {{- if .Values.hostPorts.enabled }}
              hostPort: {{ .Values.hostPorts.dnsUdp }}
              {{- end }}
            - name: dns-tcp
              containerPort: {{ .Values.service.dnsTcpPort }}
              protocol: TCP
              {{- if .Values.hostPorts.enabled }}
              hostPort: {{ .Values.hostPorts.dnsTcp }}
              {{- end }}
            - name: http
              containerPort: {{ .Values.service.setupPort }}
              protocol: TCP
            - name: web
              containerPort: {{ .Values.service.webPort }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: {{ .Values.persistence.mounts.work.mountPath }}
              subPath: {{ .Values.persistence.mounts.work.subPath }}
            - name: config
              mountPath: {{ .Values.persistence.mounts.conf.mountPath }}
              subPath: {{ .Values.persistence.mounts.conf.subPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "adguard.persistence.claimName" . }}
