apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard.fullname" . }}-setup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adguard.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "adguard.selectorLabels" . | nindent 4 }}
  ports:
    - name: setup
      port: {{ .Values.service.setupPort }}
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adguard.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "adguard.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.webPort }}
      targetPort: web
      protocol: TCP
