replicaCount: 1

image:
  repository: adguard/adguardhome
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  setupPort: 3000
  webPort: 80
  dnsTcpPort: 53
  dnsUdpPort: 53

hostPorts:
  enabled: true
  dnsTcp: 53
  dnsUdp: 53

ingress:
  enabled: true
  className: traefik
  host: ""
  subdomain: adguard
  domain: tanello.site

persistence:
  enabled: true
  existingClaim: ""
  claimName: adguard-config
  volumeName: adguard-config
  storageClassName: adguard-local
  accessMode: ReadWriteOnce
  size: 5Gi
  reclaimPolicy: Retain
  hostPath: /srv/k3s/applications/adguard
  hostPathType: DirectoryOrCreate
  mounts:
    work:
      mountPath: /opt/adguardhome/work
      subPath: work
    conf:
      mountPath: /opt/adguardhome/conf
      subPath: conf

env: {}

resources: {}
